Repository cs361fall2018/project-cartershanesachingrayland, pull requests merged in 2018-10, with the labels that each got.

#13 Attack function logic (NEW)
  src/main/java/cs361/battleships/models/Board.java
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: feature

#23 Ship test
  src/test/java/cs361/battleships/models/GameTest.java
  src/test/java/cs361/battleships/models/ShipTest.java
Labels: enhancement

#50 Fixed the no highlight issue
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
Labels: bug

#51 Added red x to placements on already occupied squares
  src/main/java/assets/game.js
Labels: bug

#57 Fixed the modal bottom cut off
  src/main/java/assets/css/custom.css
Labels: bug

#59 Add row and column headers
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/views/ApplicationController/index.ftl.html
Labels: enhancement
