Repository cs361fall2018/project-cartershanesachingrayland, pull requests merged in 2018-11, with the labels that each got.

#67 Add radar button
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/controllers/ApplicationController.java
  src/main/java/controllers/AttackGameAction.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/views/ApplicationController/index.ftl.html
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/GameTest.java
Labels: feature

#75 Backend radar
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/AtackStatus.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/CaptainQuarter.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Ship.java
  src/main/java/cs361/battleships/models/Square.java
  src/main/java/views/ApplicationController/index.ftl.html
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/GameTest.java
  src/test/java/cs361/battleships/models/SquareTest.java
Labels: feature

#76 Backend radar
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
Labels: bug

#78 Cq logic
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Square.java
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/GameTest.java
Labels: feature

#82 Fix radar bug
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
Labels: bug

#85 Java class refactor
  src/main/java/controllers/ApplicationController.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/GameTest.java
Labels: bug, enhancement

#86 Cleanup
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
Labels: enhancement

#98 Spacelaser
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/controllers/ApplicationController.java
  src/main/java/controllers/AttackGameAction.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Result.java
  src/test/java/cs361/battleships/models/GameTest.java
  src/test/java/cs361/battleships/models/LaserTest.java
  src/test/java/cs361/battleships/models/ResultTest.java
  src/test/java/cs361/battleships/models/SubmarineTest.java
Labels: feature

#100 Fix submarine issue
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/Game.java
Labels: bug
